### ISSUE TITLE
gem5 ARM full system fs.py linux kernel boot does not work / fails/ hangs with more than 8 cores: 16, 32, 64, 128, 256

### ISSUE THREAD

**Issue by cirosantilli-work** [cirosantilli-work/gem5-issues#13]
Answer: https://stackoverflow.com/questions/50248067/how-to-run-a-gem5-arm-aarch64-full-system-simulation-with-fs-py-with-more-than-8/50248068#50248068

**Comment by theverytak** [comment]
My understanding is:

1. use [4.15 kernel ](https://gem5.googlesource.com/arm/linux/+/refs/heads/gem5/v4.15)
2. add `root.system.realview.gic.gem5_extensions = True` in the last part of `fs.py`
3. make a decent .dtb file

What did I miss? Is there any certain gem5 version that I need for 16+ cores simulation?
I'm still suffering from `simulate() limit reached` or hanging when using `--timesync` option. :(

**Comment by cirosantilli2** [comment]
@theverytak I've just tested https://github.com/cirosantilli/linux-kernel-module-cheat/tree/bab029f60656913b5dea629a220ae593cc16147d#gem5-arm-full-system-with-more-than-8-cores and it worked (reaches `FATAL: kernel too old` but that is a glibc setup problem incompatible with old kernel, not a gem5 issue).

Try to reproduce and diff out your problem. You can get full CLIs from that repo without building with `--dry-run`: https://github.com/cirosantilli/linux-kernel-module-cheat/tree/bab029f60656913b5dea629a220ae593cc16147d#dry-run-to-get-commands-for-your-project
